version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/url_shortner
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: ./stopapp.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: ./runapp.sh
      timeout: 60
      runas: ubuntu
